import React from 'react';
import styles from './styles.module.css';
import { Metadata } from 'next/types';


export const metadata: Metadata = {
    title: "My About page",
    description: "This page was generated by me while learning about metadata",
  };
  
const AboutLayout = ({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) =>{
    return (
    <>
    <nav>About Navbar</nav>
    <main className={styles.main}>{children}</main>
    </>
  )
}

export default AboutLayout
